services:
  app:
    build:
      context: ./
      dockerfile: Containerfile
      args:
        - E2E=true
    image: test
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - 8000:8000
    container_name: test

  db:
    image: docker.io/postgres:15.2-alpine
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    container_name: test_db
