services:
  app:
    build:
      context: ./
      dockerfile: dev.Containerfile
    image: dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./:/opt/app-root/src
    ports:
      - 3000:3000
      - 8000:8000
    container_name: dev

  db:
    image: docker.io/postgres:15.2-alpine
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/data
    container_name: dev_db

volumes:
  pg_data:
